# Generated by Django 3.2.13 on 2022-08-04 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0006_auto_20220804_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='link1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='link2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='link3',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
