# Generated by Django 3.2.13 on 2022-08-04 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0008_auto_20220804_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
