# Generated by Django 3.2.13 on 2022-08-04 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0011_alter_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='iduser',
            new_name='id_user',
        ),
    ]
