# Generated by Django 3.2.13 on 2022-08-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0014_auto_20220805_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociallink',
            name='site_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='link',
            field=models.URLField(max_length=150, null=True),
        ),
    ]
