# Generated by Django 3.2.13 on 2022-08-18 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0015_auto_20220805_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
