# Generated by Django 3.2.13 on 2022-08-20 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0017_historyitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyitem',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
