# Generated by Django 3.2.13 on 2022-08-21 16:45

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0018_alter_historyitem_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=200)),
                ('post_image', models.ImageField(blank=True, upload_to='post-images/', verbose_name='image')),
                ('post_text', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('no_of_applause', models.IntegerField(default=0)),
            ],
        ),
    ]
